{
  "formatVersion": "1.1",
  "component": {
    "url": "../../api/1.0/api-1.0.module",
    "group": "ru.landgrafhomyak.illlos",
    "module": "api",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api.klib",
          "url": "api-mingwx64-1.0.klib",
          "size": 21838,
          "sha512": "6ed3ef8fc61165fd669fc9dd108347ca9a1b93f92d5114be3b920921ecbfc1559325e36ab21885e5c2b21e8f63ee8a2f505cce9a19220d516bba2b7109960b0d",
          "sha256": "8a7617da37b3631465b58b93c73dd227a84784af3334e162826192aca16d2f24",
          "sha1": "dc2da5efe5a5355a6097ab5789d56f500296c2c2",
          "md5": "e070fb3c3af2ab8ea14b4087874818fa"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "api-mingwx64-1.0-sources.jar",
          "url": "api-mingwx64-1.0-sources.jar",
          "size": 6800,
          "sha512": "bea5b028f05637681e6b4751677d822ae9839801ad1171a8de7376c579cd0bf247608ee0c5b4c9a25b5190c5668573670afd2ef9785723c981233df3ee4ebb9b",
          "sha256": "76815cf9c54ccdbe9fdf9a4b2bf427247c7323e74263f38b4ce32016db41276f",
          "sha1": "b784ff7cf36fb15575a0ec4fda3bcd9c2c33b187",
          "md5": "0af73aa507ef928ce5db87f6abfb1bbf"
        }
      ]
    }
  ]
}
