{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.landgrafhomyak.illlos",
    "module": "api",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-metadata-1.0.jar",
          "url": "api-1.0.jar",
          "size": 6232,
          "sha512": "9c14523dff9fd54dca3b19c998111463f9998d434c6f704e5b7c7dbecac6052536a3498d03c5271779b69d4cc0169a64e2fb47061616dde93ea068a3ec758dd3",
          "sha256": "9a7759a689d865342612d8228971d4d05b22cdd43ec5abe1d217ad742df7fe2a",
          "sha1": "8e2acd6a6a82d3deae75179e28fdd32d14b6ca19",
          "md5": "8b3934589327e8e05af0708b10f823c1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "api-kotlin-1.0-sources.jar",
          "url": "api-1.0-sources.jar",
          "size": 6800,
          "sha512": "bea5b028f05637681e6b4751677d822ae9839801ad1171a8de7376c579cd0bf247608ee0c5b4c9a25b5190c5668573670afd2ef9785723c981233df3ee4ebb9b",
          "sha256": "76815cf9c54ccdbe9fdf9a4b2bf427247c7323e74263f38b4ce32016db41276f",
          "sha1": "b784ff7cf36fb15575a0ec4fda3bcd9c2c33b187",
          "md5": "0af73aa507ef928ce5db87f6abfb1bbf"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-androidnativearm32/1.0/api-androidnativearm32-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-androidnativearm32",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-androidnativearm32/1.0/api-androidnativearm32-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-androidnativearm32",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-androidnativearm64/1.0/api-androidnativearm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-androidnativearm64",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-androidnativearm64/1.0/api-androidnativearm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-androidnativearm64",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-androidnativex64/1.0/api-androidnativex64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-androidnativex64",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-androidnativex64/1.0/api-androidnativex64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-androidnativex64",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-androidnativex86/1.0/api-androidnativex86-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-androidnativex86",
        "version": "1.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-androidnativex86/1.0/api-androidnativex86-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-androidnativex86",
        "version": "1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosarm64/1.0/api-iosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosarm64/1.0/api-iosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosarm64/1.0/api-iosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iossimulatorarm64/1.0/api-iossimulatorarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iossimulatorarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iossimulatorarm64/1.0/api-iossimulatorarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iossimulatorarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iossimulatorarm64/1.0/api-iossimulatorarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iossimulatorarm64",
        "version": "1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosx64/1.0/api-iosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iosx64",
        "version": "1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosx64/1.0/api-iosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iosx64",
        "version": "1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosx64/1.0/api-iosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-iosx64",
        "version": "1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../api-js/1.0/api-js-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../api-js/1.0/api-js-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../api-js/1.0/api-js-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-js",
        "version": "1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../api-jvm/1.0/api-jvm-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../api-jvm/1.0/api-jvm-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../api-jvm/1.0/api-jvm-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-linuxarm64/1.0/api-linuxarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-linuxarm64",
        "version": "1.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-linuxarm64/1.0/api-linuxarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-linuxarm64",
        "version": "1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-linuxx64/1.0/api-linuxx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-linuxx64",
        "version": "1.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-linuxx64/1.0/api-linuxx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-linuxx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-macosarm64/1.0/api-macosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-macosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-macosarm64/1.0/api-macosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-macosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-macosarm64/1.0/api-macosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-macosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-macosx64/1.0/api-macosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-macosx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-macosx64/1.0/api-macosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-macosx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-macosx64/1.0/api-macosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-macosx64",
        "version": "1.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-mingwx64/1.0/api-mingwx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-mingwx64",
        "version": "1.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-mingwx64/1.0/api-mingwx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-mingwx64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-tvosarm64/1.0/api-tvosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-tvosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-tvosarm64/1.0/api-tvosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-tvosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-tvosarm64/1.0/api-tvosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-tvosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-tvosx64/1.0/api-tvosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-tvosx64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-tvosx64/1.0/api-tvosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-tvosx64",
        "version": "1.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-tvosx64/1.0/api-tvosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-tvosx64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosarm32/1.0/api-watchosarm32-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosarm32",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosarm32/1.0/api-watchosarm32-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosarm32",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosarm32/1.0/api-watchosarm32-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosarm32",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosarm64/1.0/api-watchosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosarm64/1.0/api-watchosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosarm64/1.0/api-watchosarm64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosarm64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosx64/1.0/api-watchosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosx64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosx64/1.0/api-watchosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosx64",
        "version": "1.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-watchosx64/1.0/api-watchosx64-1.0.module",
        "group": "ru.landgrafhomyak.illlos",
        "module": "api-watchosx64",
        "version": "1.0"
      }
    }
  ]
}
