{
  "formatVersion": "1.1",
  "component": {
    "url": "../../api/1.0/api-1.0.module",
    "group": "ru.landgrafhomyak.illlos",
    "module": "api",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "api.klib",
          "url": "api-androidnativearm32-1.0.klib",
          "size": 21870,
          "sha512": "1e5fdcd4ec853a53ac5879c78610565974ae528aacae1db01e6dffb5724ace0788b674f5e424e28d81cc51ccce0d2d6b41edae39c9574b606a54bfb9bd3ec139",
          "sha256": "b6a417f84fcf989be615e587ad94b96241938d41ffee610042c049bf3f0f8955",
          "sha1": "37648f2bed6c9017b4bb7966bc84ce92ef73f599",
          "md5": "ad5224f9e99673d6c3c6a51c68606974"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "api-androidnativearm32-1.0-sources.jar",
          "url": "api-androidnativearm32-1.0-sources.jar",
          "size": 6800,
          "sha512": "bea5b028f05637681e6b4751677d822ae9839801ad1171a8de7376c579cd0bf247608ee0c5b4c9a25b5190c5668573670afd2ef9785723c981233df3ee4ebb9b",
          "sha256": "76815cf9c54ccdbe9fdf9a4b2bf427247c7323e74263f38b4ce32016db41276f",
          "sha1": "b784ff7cf36fb15575a0ec4fda3bcd9c2c33b187",
          "md5": "0af73aa507ef928ce5db87f6abfb1bbf"
        }
      ]
    }
  ]
}
